version: '3.7'
services:
  dumb-app:
    container_name: dumb-app
    build:
      context: ./
      dockerfile: './docker-config/dumb-app/Dockerfile'
      cache_from: 
        - python:3.7-alpine
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: > 
      sh -c "python manage.py runserver 0.0.0.0:8000"